apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-deployment
  labels:
    app: customers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
        - name: customers
          image: gcr.io/bootiful/customers
          env:
            - name: SERVER_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              hostPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
spec:
  selector:
    app: customers
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP